In [1]:
import pandas as pd
# pd.set_option('display.max_colwidth', 500)
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import _pickle as pickle
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cluster import AgglomerativeClustering, KMeans
from sklearn.metrics import calinski_harabasz_score, silhouette_score, davies_bouldin_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from tqdm import tqdm_notebook as tqdm

In [14]:
with open("refined_cluster.pkl",'rb') as fp:
    df = pickle.load(fp)

In [15]:
with open('refined_cluster.pkl', 'wb') as filehandler:
    pickle.dump(df, filehandler)

In [16]:
with open("refined_cluster.pkl",'rb') as fp:
    df1 = pickle.load(fp)

In [17]:
df1

,Bios,Movies,Religion,Music,Politics,Social Media,Sports,Age,Cluster #
0,Typical twitter fanatic. Infuriatingly humble ...,Thriller Action,Buddhist,Gospel Pop Rock,Progressive,Twitter Reddit Instagram,Basketball Football Hockey,19,1
1,Web junkie. Analyst. Infuriatingly humble intr...,Comedy Drama,Spiritual,HipHop Pop,Conservative,Twitter Facebook,Basketball Soccer Hockey,19,0
2,Avid web maven. Food practitioner. Gamer. Twit...,Horror Comedy,Christian,HipHop Rock,Moderate,Reddit Youtube,Baseball Football,21,1
3,Twitteraholic. Extreme web fanatic. Food buff....,Adventure Comedy,Agnostic,Rock,Moderate,Facebook Youtube,Basketball Football Hockey,25,1
4,Bacon enthusiast. Falls down a lot. Freelance ...,Action Adventure Drama,Hindu,Latin Rock HipHop,Conservative,Twitter TikTok Youtube,Hockey Football Basketball,19,0
...,...,...,...,...,...,...,...,...,...
6595,Typical pop culture nerd. Infuriatingly humble...,Thriller Comedy Action,Catholic,Pop Rock HipHop,Liberal,Facebook Reddit Youtube,Baseball,28,1
6596,Avid web junkie. Lifelong alcohol guru. Hardco...,Action Horror,Spiritual,Rock Classical,Conservative,Facebook Instagram Youtube,Baseball Hockey,24,1
6597,Music ninja. Bacon fanatic. Reader. Total comm...,Adventure Drama,Catholic,Country HipHop,Progressive,Facebook Youtube,Football Basketball,24,1
6598,Communicator. Bacon lover. Award-winning intro...,Adventure Drama,Christian,Country Pop Rock,Moderate,Pinterest Facebook Reddit,Baseball Football,20,1
6599,Unapologetic tv aficionado. Devoted twitter en...,Adventure RomCom Drama,Catholic,Pop Rock,Conservative,Twitter Youtube,Baseball Hockey,19,1

In [9]:
df

,Age,advocate,aficionado,alcohol,alcoholaholic,amateur,analyst,animals,apathy,avid,...,tiktok,twitter,youtube,baseball,basketball,football,hockey,other,soccer,Cluster #
0,0.032258,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1
1,0.032258,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0
2,0.096774,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1
3,0.225806,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1
4,0.032258,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6595,0.322581,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1
6596,0.193548,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1
6597,0.193548,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1
6598,0.064516,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1
6599,0.032258,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1